# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imgprocess.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10imgprocess.proto\"!\n\x11ImgProcessRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x0fImgProcessReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32\x44\n\x0cImgProcesser\x12\x34\n\nImgProcess\x12\x12.ImgProcessRequest\x1a\x10.ImgProcessReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imgprocess_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMGPROCESSREQUEST']._serialized_start=20
  _globals['_IMGPROCESSREQUEST']._serialized_end=53
  _globals['_IMGPROCESSREPLY']._serialized_start=55
  _globals['_IMGPROCESSREPLY']._serialized_end=103
  _globals['_IMGPROCESSER']._serialized_start=105
  _globals['_IMGPROCESSER']._serialized_end=173
# @@protoc_insertion_point(module_scope)
