# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
try:
    from api.imgprocess.v1 import imgprocess_pb2 as imgprocess__pb2
except ModuleNotFoundError:
    from qt0223.api.imgprocess.v1 import imgprocess_pb2 as imgprocess__pb2


class ImgProcesserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImgProcess = channel.unary_unary(
                '/ImgProcesser/ImgProcess',
                request_serializer=imgprocess__pb2.ImgProcessRequest.SerializeToString,
                response_deserializer=imgprocess__pb2.ImgProcessReply.FromString,
                )


class ImgProcesserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImgProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImgProcesserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImgProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.ImgProcess,
                    request_deserializer=imgprocess__pb2.ImgProcessRequest.FromString,
                    response_serializer=imgprocess__pb2.ImgProcessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImgProcesser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImgProcesser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImgProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImgProcesser/ImgProcess',
            imgprocess__pb2.ImgProcessRequest.SerializeToString,
            imgprocess__pb2.ImgProcessReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
