# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupdate.proto\"\x1d\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x0bUpdateReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32;\n\x07Updater\x12\x30\n\x0eUpdateSoftware\x12\x0e.UpdateRequest\x1a\x0c.UpdateReply\"\x00\x42\x1eZ\x1cqt0223/api/helloworld/v1;v1;b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034qt0223/api/helloworld/v1;v1;'
  _globals['_UPDATEREQUEST']._serialized_start=16
  _globals['_UPDATEREQUEST']._serialized_end=45
  _globals['_UPDATEREPLY']._serialized_start=47
  _globals['_UPDATEREPLY']._serialized_end=91
  _globals['_UPDATER']._serialized_start=93
  _globals['_UPDATER']._serialized_end=152
# @@protoc_insertion_point(module_scope)
